# Generated by Django 5.0.1 on 2024-02-18 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_category_alter_post_pub_date_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 11, 6, 0, 503524, tzinfo=datetime.timezone.utc)),
        ),
    ]
