# Generated by Django 5.0.1 on 2024-02-18 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 11, 13, 21, 928196, tzinfo=datetime.timezone.utc)),
        ),
    ]
