# Generated by Django 5.0.1 on 2024-04-27 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_post_pub_date_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='Posts', to='Blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 10, 9, 36, 254736, tzinfo=datetime.timezone.utc)),
        ),
    ]
